# Generated by Django 5.1.4 on 2024-12-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moveie',
            new_name='Movie',
        ),
    ]
